" Vim syntax file
" Language:     SQL, PL/pgSQL, PL/Python (PostgreSQL 9.5)
" Author:       space::tekk
" Maintainer:   Lifepillar

if version < 600
  syntax clear
elseif exists("b:current_syntax")
  finish
endif

syn case ignore

syn keyword sqlSpecial   false null true

" SQL keywords (see Table C-1 in App. C of PostgreSQL manual)
syn keyword sqlKeyword   abort abs absent absolute access according action ada add admin after array
syn keyword sqlKeyword   aggregate allocate also always analyse are array_agg array_max_cardinality as
syn keyword sqlKeyword   asc asensitive assertion assignment asymmetric at atomic attribute attributes
syn keyword sqlKeyword   authorization avg backward base64 before begin begin_frame begin_partition
syn keyword sqlKeyword   bernoulli binary bit_length blob blocked bom both breadth by cache call called
syn keyword sqlKeyword   cardinality cascade cascaded case cast catalog catalog_name ceil ceiling chain
syn keyword sqlKeyword   characteristics characters character_length character_set_catalog
syn keyword sqlKeyword   character_set_name character_set_schema char_length check checkpoint class
syn keyword sqlKeyword   class_origin clob close cluster coalesce cobol collate collation
syn keyword sqlKeyword   collation_catalog collation_name collation_schema collect column columns
syn keyword sqlKeyword   column_name command_function command_function_code comments committed
syn keyword sqlKeyword   concurrently condition condition_number configuration conflict connect
syn keyword sqlKeyword   connection connection_name constraint constraints constraint_catalog
syn keyword sqlKeyword   constraint_name constraint_schema constructor content continue contains
syn keyword sqlKeyword   control conversion convert corr corresponding cost count covar_pop covar_samp
syn keyword sqlKeyword   cross csv cube cume_dist current current_catalog current_date
syn keyword sqlKeyword   current_default_transform_group current_path current_role current_row
syn keyword sqlKeyword   current_schema current_time current_timestamp current_transform_group_for_type
syn keyword sqlKeyword   current_user cursor cursor_name cycle data database datalink
syn keyword sqlKeyword   datetime_interval_code datetime_interval_precision day db deallocate dec
syn keyword sqlKeyword   declare default defaults deferrable deferred defined definer degree delimiter
syn keyword sqlKeyword   delimiters dense_rank depth deref derived desc describe descriptor
syn keyword sqlKeyword   deterministic diagnostics dictionary disable discard disconnect dispatch
syn keyword sqlKeyword   dlnewcopy dlpreviouscopy dlurlcomplete dlurlcompleteonly dlurlcompletewrite
syn keyword sqlKeyword   dlurlpath dlurlpathonly dlurlpathwrite dlurlscheme dlurlserver dlvalue do
syn keyword sqlKeyword   document domain dynamic dynamic_function dynamic_function_code each element
syn keyword sqlKeyword   else empty enable encoding encrypted end end-exec end_frame end_partition
syn keyword sqlKeyword   enforced equals event every exception exclude excluding exclusive exec exp
syn keyword sqlKeyword   expression extension external extract family fetch file filter final first
syn keyword sqlKeyword   first_value flag floor following for force foreign fortran forward found
syn keyword sqlKeyword   frame_row free freeze from fs full function functions fusion general generated
syn keyword sqlKeyword   get global go goto granted greatest group grouping groups handler having
syn keyword sqlKeyword   header hex hierarchy hold hour id identity if ignore immediate immediately
syn keyword sqlKeyword   immutable implementation implicit import including increment indent index
syn keyword sqlKeyword   indexes indicator inherit inherits initially inline inner inout input
syn keyword sqlKeyword   insensitive instance instantiable instead integrity intersection into invoker
syn keyword sqlKeyword   is isnull isolation join key key_member key_type label lag language large last
syn keyword sqlKeyword   last_value lateral lead leading leakproof least left length level library
syn keyword sqlKeyword   like_regex limit link listen ln load local localtime localtimestamp location
syn keyword sqlKeyword   locator locked logged lower map mapping match matched materialized max
syn keyword sqlKeyword   maxvalue max_cardinality member merge message_length message_octet_length
syn keyword sqlKeyword   message_text method min minute minvalue mod mode modifies module month more
syn keyword sqlKeyword   move multiset mumps name names namespace national natural nchar nclob nesting
syn keyword sqlKeyword   new next nfc nfd nfkc nfkd nil no none normalize normalized not nothing notify
syn keyword sqlKeyword   notnull nowait nth_value ntile nullable nullif nulls number object
syn keyword sqlKeyword   occurrences_regex octets octet_length of off offset oids old on only open
syn keyword sqlKeyword   operator option options or order ordering ordinality others out outer output
syn keyword sqlKeyword   over overlaps overlay overriding owned owner pad parameter parameter_mode
syn keyword sqlKeyword   parameter_name parameter_ordinal_position parameter_specific_catalog
syn keyword sqlKeyword   parameter_specific_name parameter_specific_schema parser partial partition
syn keyword sqlKeyword   pascal passing passthrough password percent percentile_cont percentile_disc
syn keyword sqlKeyword   percent_rank period permission placing plans pli policy portion position
syn keyword sqlKeyword   position_regex power precedes preceding precision prepare prepared preserve
syn keyword sqlKeyword   primary prior privileges procedural procedure program public quote range rank
syn keyword sqlKeyword   read reads real reassign recheck recovery recursive ref references referencing
syn keyword sqlKeyword   refresh regr_avgx regr_avgy regr_count regr_intercept regr_r2 regr_slope
syn keyword sqlKeyword   regr_sxx regr_sxy regr_syy reindex relative release rename repeatable replace
syn keyword sqlKeyword   replica requiring reset respect restart restore restrict result return
syn keyword sqlKeyword   returned_cardinality returned_length returned_octet_length returned_sqlstate
syn keyword sqlKeyword   returning returns right role rollup routine routine_catalog routine_name
syn keyword sqlKeyword   routine_schema row rows row_count row_number rule scale schema schema_name
syn keyword sqlKeyword   scope scope_catalog scope_name scope_schema scroll search second section
syn keyword sqlKeyword   security selective self sensitive sequence sequences serializable server
syn keyword sqlKeyword   server_name session session_user setof sets share show similar simple size
syn keyword sqlKeyword   skip snapshot some source space specific specifictype specific_name sql
syn keyword sqlKeyword   sqlcode sqlerror sqlexception sqlstate sqlwarning sqrt stable standalone start
syn keyword sqlKeyword   state statement static statistics stddev_pop stddev_samp stdin stdout storage
syn keyword sqlKeyword   strict strip structure style subclass_origin submultiset substring
syn keyword sqlKeyword   substring_regex succeeds sum symmetric sysid system system_time system_user
syn keyword sqlKeyword   table tables tablesample tablespace table_name temp template temporary then
syn keyword sqlKeyword   ties timezone_hour timezone_minute to token top_level_count trailing
syn keyword sqlKeyword   transaction transactions_committed transactions_rolled_back transaction_active
syn keyword sqlKeyword   transform transforms translate translate_regex translation treat trigger
syn keyword sqlKeyword   trigger_catalog trigger_name trigger_schema trim trim_array trusted type types
syn keyword sqlKeyword   uescape unbounded uncommitted under unencrypted union unique unknown unlink
syn keyword sqlKeyword   unlisten unlogged unnamed unnest until untyped upper uri usage user
syn keyword sqlKeyword   user_defined_type_catalog user_defined_type_code user_defined_type_name
syn keyword sqlKeyword   user_defined_type_schema using vacuum valid validate validator value values
syn keyword sqlKeyword   value_of varbinary variadic var_pop var_samp verbose version versioning view
syn keyword sqlKeyword   views volatile when whenever where whitespace width_bucket window with within
syn keyword sqlKeyword   without work wrapper write xmlagg xmlattributes xmlbinary xmlcast xmlcomment
syn keyword sqlKeyword   xmlconcat xmldeclaration xmldocument xmlelement xmlexists xmlforest xmliterate
syn keyword sqlKeyword   xmlnamespaces xmlparse xmlpi xmlquery xmlroot xmlschema xmlserialize xmltable
syn keyword sqlKeyword   xmltext xmlvalidate year yes zone
" PL/pgSQL
syn keyword sqlKeyword contained alias all array as begin by case close collate column constant
syn keyword sqlKeyword contained constraint continue current current cursor datatype declare
syn keyword sqlKeyword contained detail diagnostics else elsif end errcode exception execute
syn keyword sqlKeyword contained exit fetch fetch for foreach forward found from get hint if
syn keyword sqlKeyword contained into last loop message move next no notice open perform prepare
syn keyword sqlKeyword contained query raise relative return reverse rowtype schema
syn keyword sqlKeyword contained scroll slice sqlstate stacked strict table tg_argv tg_event
syn keyword sqlKeyword contained tg_level tg_name tg_nargs tg_op tg_relid tg_relname
syn keyword sqlKeyword contained tg_table_name tg_table_schema tg_tag tg_when then type using
syn keyword sqlKeyword contained while

" Functions
" To get the list of all PostgreSQL functions, give the following commands
" (this assumes that template1 has not been modified from its default):
"
" psql template1
" \t
" \o functions.txt
" select  distinct p.proname
" from    pg_catalog.pg_namespace n
" join    pg_catalog.pg_proc p
" on      p.pronamespace = n.oid;
syn keyword sqlFunction repeat jsonb_object_field texticregexeq pg_stat_get_buf_alloc to_regtype
syn keyword sqlFunction int28ge timestamptz_eq_timestamp int8div lo_creat bool_alltrue macaddr_lt
syn keyword sqlFunction interval_in inet_same_family pg_relation_filepath biteq
syn keyword sqlFunction has_type_privilege jsonb_delete text_lt regexp_split_to_table
syn keyword sqlFunction json_object_agg_transfn tsquery_cmp gist_box_same timestamptz_gt
syn keyword sqlFunction textnlike date_ge numeric_div_trunc timestamptz_le_timestamp tintervalne
syn keyword sqlFunction brinvacuumcleanup interval_larger regclassin gin_extract_jsonb
syn keyword sqlFunction regdictionaryrecv unnest cash_in numeric_div jsonb_each btfloat8cmp
syn keyword sqlFunction smgreq close_lseg jsonb_object_keys numerictypmodin varbit_recv int8send
syn keyword sqlFunction timestamptz_lt_timestamp pg_tablespace_size iso_to_win866
syn keyword sqlFunction elem_contained_by_range varbit_transform gtsvectorout regprocin
syn keyword sqlFunction varcharrecv poly_overabove gist_point_consistent anyarray_send sign
syn keyword sqlFunction brin_inclusion_consistent trigger_out point_vert lead RI_FKey_setnull_upd
syn keyword sqlFunction hashgettuple tidsend pt_contained_circle circle_left btboolcmp
syn keyword sqlFunction pg_stat_get_backend_pid gtsvector_consistent timestamptz
syn keyword sqlFunction int8_avg_accum_inv abstimeeq tsrange time_out poly_center setval xml_send
syn keyword sqlFunction pg_function_is_visible btbuildempty inet_server_port convert_to
syn keyword sqlFunction network_larger poly_above spg_kd_choose timestamptz_ge tsquery_or
syn keyword sqlFunction bitshiftright regconfigrecv float8mul rangesel point_in ts_token_type
syn keyword sqlFunction poly_left table_to_xml_and_xmlschema dsqrt byteacat json_to_recordset
syn keyword sqlFunction pg_stat_get_backend_xact_start reltimesend pg_stat_get_blocks_fetched
syn keyword sqlFunction bytealike txid_snapshot_xmin dcbrt domain_recv networkjoinsel reltimerecv
syn keyword sqlFunction range_overright regprocout iso8859_1_to_utf8 tintervalsame point_eq
syn keyword sqlFunction int48ge date_ne namelt box_overlap int2larger network_gt
syn keyword sqlFunction gin_extract_jsonb_path binary_upgrade_set_next_toast_pg_type_oid char
syn keyword sqlFunction float84mul timetztypmodout fmgr_internal_validator int2gt numeric_in
syn keyword sqlFunction float4smaller spg_text_inner_consistent numeric_lt schema_to_xmlschema
syn keyword sqlFunction to_tsquery pi range_minus tsm_handler_in cash_out bitand big5_to_mic
syn keyword sqlFunction brinrescan pg_show_all_settings textregexne mktinterval int84pl
syn keyword sqlFunction pg_stat_get_last_analyze_time timestamp_eq_timestamptz time_gt date_mi
syn keyword sqlFunction win866_to_iso date_part hashenum btcharcmp ts_parse bitor
syn keyword sqlFunction pg_stat_get_bgwriter_buf_written_checkpoints lower_inf hashoidvector
syn keyword sqlFunction float8_regr_avgx byteane _pg_index_position to_ascii tintervallenne
syn keyword sqlFunction string_agg pg_get_object_address json_object_field_text array_positions
syn keyword sqlFunction pg_last_xlog_replay_location range_cmp lseg_perp tan json_each_text
syn keyword sqlFunction time_in sin cursor_to_xmlschema uuid_gt similar_escape
syn keyword sqlFunction brin_inclusion_union timestamptz_send regoperatorout box_lt oidlarger
syn keyword sqlFunction path_n_ge point_sub line_vertical get_bit int4larger abstimegt
syn keyword sqlFunction int8_avg_accum inet_merge round textcat ginarrayextract set_byte
syn keyword sqlFunction pg_replication_origin_session_is_setup brincostestimate date_mii
syn keyword sqlFunction make_interval pg_ts_template_is_visible utf8_to_big5 int2out
syn keyword sqlFunction percentile_cont_float8_final dsimple_lexize on_ppath booleq
syn keyword sqlFunction bpcharicregexeq network_ne regtypein oidsmaller bitne gist_point_fetch
syn keyword sqlFunction pg_replication_origin_session_reset area uuid_in
syn keyword sqlFunction schema_to_xml_and_xmlschema shell_out int8shr numeric_avg_accum
syn keyword sqlFunction range_contains_elem box_out int2or range_out int4pl bpchargt tsvector_lt
syn keyword sqlFunction ginbuild spgvacuumcleanup string_agg_transfn uuid_recv int8not
syn keyword sqlFunction has_column_privilege date_gt_timestamp nameicnlike win866_to_koi8r
syn keyword sqlFunction anytextcat float48gt circle_contain int4or pg_stat_get_blocks_hit
syn keyword sqlFunction brin_minmax_opcinfo pg_stat_get_mod_since_analyze float48ge macaddr_out
syn keyword sqlFunction pg_lsn_hash pg_stat_get_db_conflict_all circle_recv like_escape bitlt
syn keyword sqlFunction date_cmp_timestamp has_database_privilege jsonb_recv poly_contain int4out
syn keyword sqlFunction tidlt isparallel int2xor float4recv cstring_out
syn keyword sqlFunction pg_stat_reset_single_table_counters pg_read_binary_file box_contained
syn keyword sqlFunction cidr_send percentile_cont_float8_multi_final latin4_to_mic range_send
syn keyword sqlFunction tintervalct int8_accum_inv regconfigout box_center textlike boolin
syn keyword sqlFunction pg_char_to_encoding pg_available_extensions
syn keyword sqlFunction pg_stat_get_db_conflict_tablespace gin_tsquery_consistent ts_stat
syn keyword sqlFunction box_left timestamp_ge btarraycmp time_send int24ne
syn keyword sqlFunction pg_stat_get_db_temp_bytes gist_bbox_distance timestamp_lt varcharin
syn keyword sqlFunction pg_stat_get_buf_written_backend pg_stat_get_db_deadlocks
syn keyword sqlFunction gin_triconsistent_jsonb lseg_ne pg_stat_get_db_numbackends
syn keyword sqlFunction jsonb_extract_path_text mic_to_latin2 circle_center pg_ddl_command_recv
syn keyword sqlFunction isperp network_cmp sqrt pg_stat_reset_single_function_counters
syn keyword sqlFunction percentile_disc_final version int28mul ln timestamptz_cmp_date varbiteq
syn keyword sqlFunction utf8_to_gb18030 date_smaller unique_key_recheck jsonb_contained isfinite
syn keyword sqlFunction timestamptz_lt array_larger circle_right uhc_to_utf8 internal_in
syn keyword sqlFunction float8larger cidsend RI_FKey_check_ins bpcharge rank_final btrim
syn keyword sqlFunction cash_mul_int4 int2up reltimelt float84div enum_cmp gtsquery_same
syn keyword sqlFunction pg_stat_get_xact_tuples_deleted setweight varbitge
syn keyword sqlFunction pg_stat_get_bgwriter_requested_checkpoints float4in
syn keyword sqlFunction timestamptz_pl_interval _pg_numeric_precision_radix point_distance
syn keyword sqlFunction poly_distance bpchartypmodin float8le abstimerecv path_recv floor
syn keyword sqlFunction jsonb_concat texticregexne int28gt oidne euc_tw_to_mic regclassrecv
syn keyword sqlFunction smgrout btmarkpos quote_nullable int2ne spg_range_quad_picksplit
syn keyword sqlFunction tsquery_ne cash_mul_int2 macaddr_ge inetor unknownrecv
syn keyword sqlFunction pg_replication_origin_create arraycontsel record_recv utf8_to_johab
syn keyword sqlFunction _pg_numeric_precision postgresql_fdw_validator json_populate_record
syn keyword sqlFunction tsvector_concat isempty pg_stat_get_last_autovacuum_time timestamptz_out
syn keyword sqlFunction circle_same timestamptz_in isvertical timetz_mi_interval mic_to_win1250
syn keyword sqlFunction utf8_to_euc_kr xmlagg int4inc spgbuildempty btoidvectorcmp
syn keyword sqlFunction gistcostestimate bpcharout bytearecv box pg_replication_origin_xact_reset
syn keyword sqlFunction texteq dist_ppoly int82lt void_in timestamp_cmp_timestamptz
syn keyword sqlFunction intervaltypmodout network_subeq time_mi_interval regtyperecv
syn keyword sqlFunction win866_to_mic int42gt timetz_cmp tintervalle gist_point_compress cash_ge
syn keyword sqlFunction poly_in gist_box_compress jsonb_lt xidsend btbulkdelete array_remove
syn keyword sqlFunction on_pl timestamp_izone_transform float8ge bpchar_smaller pg_sleep_until
syn keyword sqlFunction mic_to_euc_jp cidr_out btgetbitmap enum_out texticnlike pg_xlogfile_name
syn keyword sqlFunction int42eq int2le pg_stat_get_autovacuum_count path_n_eq regrolein
syn keyword sqlFunction ginbeginscan point_below xmlcomment lo_import
syn keyword sqlFunction pg_try_advisory_xact_lock_shared float8_covar_samp spg_range_quad_choose
syn keyword sqlFunction pg_stat_get_db_conflict_snapshot pg_size_pretty int2send numeric_mod
syn keyword sqlFunction numeric_ge pg_is_xlog_replay_paused pg_try_advisory_lock
syn keyword sqlFunction jsonb_array_elements_text spg_quad_choose concat_ws host character_length
syn keyword sqlFunction bool_accum box_recv float4pl pg_current_xlog_location cash_div_cash cbrt
syn keyword sqlFunction jsonb_object_agg_transfn pg_ddl_command_in brin_summarize_new_values
syn keyword sqlFunction suppress_redundant_updates_trigger int2pl
syn keyword sqlFunction pg_stat_get_checkpoint_write_time abs pg_stat_get_activity regr_count
syn keyword sqlFunction regclasssend int8_sum quote_ident pg_opclass_is_visible line_send
syn keyword sqlFunction ordered_set_transition_multi pg_xlog_replay_pause int8mod jsonb_gt
syn keyword sqlFunction bpcharicnlike inetpl lo_from_bytea
syn keyword sqlFunction binary_upgrade_set_next_index_pg_class_oid set_config oidin reltimele
syn keyword sqlFunction point_ne uuid_eq hash_aclitem ts_rewrite lo_lseek64 timetypmodout int2and
syn keyword sqlFunction point text_pattern_gt ginmarkpos range_gist_same shell_in record_send
syn keyword sqlFunction iclikejoinsel jsonb_agg_finalfn txid_snapshot_send chargt array_cat
syn keyword sqlFunction timestamptz_gt_date session_user bpchar timepl hashbuild opaque_in
syn keyword sqlFunction unknownin regr_sxy pg_stat_get_xact_tuples_hot_updated tintervalleneq
syn keyword sqlFunction int24lt inet_out lseg_send int24mul hashoid abstimesend point_add degrees
syn keyword sqlFunction on_sb macaddr_ne sjis_to_utf8 iclikesel bitshiftleft likesel int4not
syn keyword sqlFunction plpgsql_validator arraycontained timestamp_eq date_ge_timestamptz
syn keyword sqlFunction pg_stat_get_tuples_fetched box_overleft timestamp factorial
syn keyword sqlFunction pg_advisory_unlock_all tsvectorout areajoinsel regr_avgy
syn keyword sqlFunction pg_total_relation_size prsd_nexttoken float4send inet_gist_same
syn keyword sqlFunction has_server_privilege tstzrange make_date timestamp_gt namerecv power
syn keyword sqlFunction networksel pg_xlog_replay_resume tsqueryin hashint4 get_current_ts_config
syn keyword sqlFunction cidrecv acos lseg_gt pg_trigger_depth text_le numeric_accum xmlvalidate
syn keyword sqlFunction float8gt array_recv timetypmodin numeric_poly_var_pop pg_get_viewdef
syn keyword sqlFunction interval_avg pg_stat_get_backend_waiting int84lt numeric_stddev_pop
syn keyword sqlFunction regnamespacein bit_or date_sortsupport numnode tintervalge
syn keyword sqlFunction pg_advisory_lock gistcanreturn latin2_to_win1250 numeric_eq dist_pl
syn keyword sqlFunction mul_d_interval record_image_lt array_ge int2_avg_accum var_samp int2shl
syn keyword sqlFunction timetz_pl_interval int42mul timetz_eq oid pg_rotate_logfile boolne
syn keyword sqlFunction btcostestimate gistrestrpos cidr txid_snapshot_out lseg_horizontal
syn keyword sqlFunction int2_accum pg_stat_get_backend_dbid regr_slope
syn keyword sqlFunction pg_last_xlog_receive_location spgcostestimate
syn keyword sqlFunction pg_stat_get_last_autoanalyze_time aclcontains strip to_tsvector
syn keyword sqlFunction pg_listening_channels namenlike float48mul pg_stat_get_backend_idset
syn keyword sqlFunction pg_terminate_backend array_typanalyze reltimege
syn keyword sqlFunction pg_replication_origin_progress lseg_parallel macaddr_and nameregexeq
syn keyword sqlFunction int8shl euc_jp_to_sjis float8mi upper regexnesel network_smaller
syn keyword sqlFunction tsvector_cmp flt8_mul_cash regr_r2 system line_out oidvectorout
syn keyword sqlFunction dist_cpoint int4and pg_lsn_ge random timestamp_cmp_date
syn keyword sqlFunction timestamp_lt_timestamptz array_prepend pg_xlog_location_diff
syn keyword sqlFunction date_ge_timestamp range_gist_decompress int4ne
syn keyword sqlFunction pg_last_xact_replay_timestamp mic_to_latin3 utf8_to_uhc
syn keyword sqlFunction binary_upgrade_set_next_array_pg_type_oid positionjoinsel uuid_hash
syn keyword sqlFunction icregexnesel iso_to_mic hashvacuumcleanup float84ge bitxor oidvectorsend
syn keyword sqlFunction network_sub lag btbpchar_pattern_cmp btrecordimagecmp bit on_pb stddev
syn keyword sqlFunction hash_array box_send json_to_record asin box_above right float48le
syn keyword sqlFunction jsonb_hash tidout int42le int42ge time_pl_interval date_eq_timestamptz
syn keyword sqlFunction float48ne enum_le gtsquery_picksplit last_value regroleout int8eq
syn keyword sqlFunction interval_lt int84mul int82ge json_object fdw_handler_out icregexnejoinsel
syn keyword sqlFunction pg_backup_start_time record_gt transaction_timestamp circle_below
syn keyword sqlFunction interval_pl_time pg_stat_get_xact_function_self_time ascii_to_mic int82le
syn keyword sqlFunction pg_xlogfile_name_offset float8um lseg_distance int24gt regr_syy
syn keyword sqlFunction language_handler_out pg_stat_get_analyze_count spgoptions
syn keyword sqlFunction pg_replication_origin_xact_setup eqsel RI_FKey_noaction_del
syn keyword sqlFunction icnlikejoinsel int8mi gistvacuumcleanup jsonb_array_length pg_backend_pid
syn keyword sqlFunction jsonb_ge float8 pg_describe_object spg_quad_inner_consistent int2mi
syn keyword sqlFunction to_timestamp nameicregexne pg_get_function_arguments inetnot
syn keyword sqlFunction numeric_smaller bttextcmp close_lb btint42cmp make_time bitle dist_pc
syn keyword sqlFunction inetand gist_circle_consistent int4range_subdiff numeric_gt int2vectorout
syn keyword sqlFunction pg_lsn_lt ts_match_vq varbitlt euc_cn_to_utf8 byteanlike
syn keyword sqlFunction brin_inclusion_add_value poly_same width_bucket col_description cideq
syn keyword sqlFunction popen timenow range_le namele int48eq circle_div_pt pg_table_size
syn keyword sqlFunction utf8_to_koi8u inet_client_port brinbulkdelete array_out
syn keyword sqlFunction pg_try_advisory_lock_shared cashsmaller numeric_sub mic_to_win866
syn keyword sqlFunction broadcast brin_minmax_union tintervallt nameout pg_options_to_table
syn keyword sqlFunction ginvacuumcleanup utf8_to_sjis inet_gist_consistent pt_contained_poly
syn keyword sqlFunction box_div date_send path_contain_pt bpcharcmp timestamptypmodin
syn keyword sqlFunction pg_stat_get_xact_function_calls pg_read_file jsonb_exists
syn keyword sqlFunction has_table_privilege win1250_to_mic circle_overright sum dround cidr_recv
syn keyword sqlFunction mic_to_koi8r pg_stat_get_backend_userid chareq
syn keyword sqlFunction pg_stat_get_db_tuples_fetched int8larger npoints nameiclike inetmi int8pl
syn keyword sqlFunction pg_filenode_relation array_agg_transfn date_gt spgendscan int24ge
syn keyword sqlFunction textregexeq timestamp_ne range_in utf8_to_ascii ascii_to_utf8 btbuild
syn keyword sqlFunction gistoptions bpchar_larger pg_ts_config_is_visible float4um box_contain
syn keyword sqlFunction pg_get_constraintdef spg_kd_picksplit numeric_poly_avg line_perp xml_out
syn keyword sqlFunction tidin path_length regprocedurerecv int8in float4_accum time_ge btint28cmp
syn keyword sqlFunction json_each regexp_split_to_array pg_typeof uuid_out float84lt path
syn keyword sqlFunction spg_quad_config scalarltsel record_image_ge loread boolgt
syn keyword sqlFunction int8range_canonical hashrestrpos pg_conf_load_time int8ge path_add
syn keyword sqlFunction spg_range_quad_inner_consistent timestamptz_le close_pl koi8r_to_win1251
syn keyword sqlFunction inetmi_int8 cstring_recv text_smaller interval_out varbit
syn keyword sqlFunction pg_stat_get_live_tuples range_eq pg_stat_get_bgwriter_stat_reset_time
syn keyword sqlFunction timestamp_recv array_to_json binary_upgrade_set_next_pg_enum_oid
syn keyword sqlFunction pg_operator_is_visible pg_extension_update_paths
syn keyword sqlFunction pg_stat_get_xact_function_total_time timestamp_gt_date poly_send
syn keyword sqlFunction set_masklen int2shr int42ne int8xor text_pattern_le to_number float8pl
syn keyword sqlFunction utf8_to_koi8r scalargtsel inet_gist_picksplit boolsend prsd_end
syn keyword sqlFunction gistbuildempty pg_stat_get_db_xact_commit octet_length network_supeq
syn keyword sqlFunction box_gt enum_eq pg_stat_get_db_conflict_lock int4abs
syn keyword sqlFunction pg_stat_get_buf_fsync_backend database_to_xmlschema
syn keyword sqlFunction gin_triconsistent_jsonb_path spg_text_config numeric_add int8smaller
syn keyword sqlFunction int4up btrescan charrecv enum_range int2in float4ge lseg_interpt
syn keyword sqlFunction datetimetz_pl poly_right gistbuild int4xor has_function_privilege int84le
syn keyword sqlFunction time_le mxid_age namein tsm_handler_out regrolesend jsonb_strip_nulls
syn keyword sqlFunction gtsvectorin current_database bit_length pg_notify date_larger interval_gt
syn keyword sqlFunction float4up float4eq gist_circle_compress mode_final macaddr_not
syn keyword sqlFunction pg_stat_get_tuples_inserted timestamp_ge_date btnamecmp jsonb_set textout
syn keyword sqlFunction binary_upgrade_set_next_pg_type_oid pg_stop_backup interval_pl_date
syn keyword sqlFunction _pg_truetypmod pg_stat_get_xact_blocks_fetched byteage spg_text_picksplit
syn keyword sqlFunction gistgetbitmap format_type pg_relation_is_updatable numeric
syn keyword sqlFunction timestamp_larger int4_mul_cash bpcharlike sjis_to_euc_jp pg_get_userbyid
syn keyword sqlFunction regexeqsel int8_accum timestamp_mi_interval record_ge range_before
syn keyword sqlFunction bttidcmp pg_has_role make_timestamptz bit_recv has_sequence_privilege
syn keyword sqlFunction text_pattern_lt pg_create_restore_point pg_collation_for ts_match_tt
syn keyword sqlFunction float4mi pg_get_keywords pg_advisory_xact_lock to_json int2eq hashinsert
syn keyword sqlFunction timestamptz_larger nameicregexeq quote_literal charge spgbuild close_sb
syn keyword sqlFunction timetz_ge hashgetbitmap interval_cmp pg_stat_get_tuples_hot_updated
syn keyword sqlFunction array_send box_overright network_lt hashfloat4 int28div float4out abbrev
syn keyword sqlFunction tintervalrel line_eq dsnowball_init RI_FKey_setdefault_upd
syn keyword sqlFunction pg_client_encoding name mic_to_latin1 int8um mode gb18030_to_utf8
syn keyword sqlFunction datetime_pl enum_ge gin_extract_jsonb_query float48div tidle
syn keyword sqlFunction pg_cancel_backend pg_stat_get_db_tuples_returned int2int4_sum tsvector_ne
syn keyword sqlFunction int84div icregexeqjoinsel gin_extract_jsonb_query_path int8lt lo_put
syn keyword sqlFunction numeric_send percentile_cont_interval_multi_final cash_le poly_npoints
syn keyword sqlFunction circle_ge float8_var_samp big5_to_euc_tw int48ne json_recv oidvectorin
syn keyword sqlFunction anyarray_out timestamptz_ge_timestamp scalargtjoinsel koi8r_to_utf8
syn keyword sqlFunction brinmarkpos ascii btreltimecmp prsd_start scalarltjoinsel regoperatorin
syn keyword sqlFunction txid_current convert_from pg_drop_replication_slot inter_sb
syn keyword sqlFunction binary_upgrade_set_next_heap_pg_class_oid brinbuild time
syn keyword sqlFunction brin_minmax_add_value tidsmaller pg_stat_get_tuples_updated radius
syn keyword sqlFunction anynonarray_in gistendscan circle_sub_pt enum_last float8eq oidge
syn keyword sqlFunction date_le_timestamptz timestamp_le point_recv areasel numeric_mul xml_recv
syn keyword sqlFunction has_any_column_privilege gistbulkdelete cash_words timedate_pl
syn keyword sqlFunction percent_rank_final _pg_datetime_precision gtsvector_penalty
syn keyword sqlFunction pg_last_committed_xact _pg_expandarray poly_overlap pg_export_snapshot
syn keyword sqlFunction line_distance string_to_array every tsvectorrecv interval_mul boolge
syn keyword sqlFunction box_ge pg_node_tree_in tintervallenle pg_column_is_updatable
syn keyword sqlFunction pg_stat_get_checkpoint_sync_time tstzrange_subdiff has_schema_privilege
syn keyword sqlFunction int8inc_any pg_type_is_visible regprocedureout interval_accum tsmatchsel
syn keyword sqlFunction bpchar_pattern_le char_length interval_ne regexp_replace
syn keyword sqlFunction gtsvector_decompress path_out pg_node_tree_recv numeric_poly_sum
syn keyword sqlFunction nameregexne hashmarkpos current_schemas ts_match_tq any_in mic_to_latin4
syn keyword sqlFunction range_gist_consistent bytea_string_agg_finalfn dsnowball_lexize pg_lsn_ne
syn keyword sqlFunction ntile range_overlaps float8_regr_sxy pg_stat_get_snapshot_timestamp
syn keyword sqlFunction enum_smaller koi8r_to_mic time_recv bittypmodout bpchar_pattern_gt
syn keyword sqlFunction inet_recv box_eq unknownout dist_ps cash_div_flt8 encode tsvector_gt
syn keyword sqlFunction fmgr_c_validator regdictionarysend pg_show_replication_origin_status
syn keyword sqlFunction json_array_elements_text rpad positionsel float8_regr_avgy
syn keyword sqlFunction json_object_field float8div range_union box_overbelow aclitemin
syn keyword sqlFunction dispell_init gin_compare_jsonb nlikejoinsel xmlexists gingetbitmap
syn keyword sqlFunction date_mi_interval jsonb_agg_transfn rank float48lt path_in
syn keyword sqlFunction gtsvector_picksplit brin_minmax_consistent int4um circle_eq btint82cmp
syn keyword sqlFunction query_to_xml_and_xmlschema netmask timestamp_le_date
syn keyword sqlFunction pg_stat_get_function_calls charout jsonb_object pg_get_replication_slots
syn keyword sqlFunction daterange_canonical int4mod prsd_lextype date_ne_timestamp cidr_in
syn keyword sqlFunction numeric_log bytea_string_agg_transfn cursor_to_xml btint4sortsupport
syn keyword sqlFunction int82mul xml_is_well_formed bytealt lseg_le icregexeqsel bpcharicregexne
syn keyword sqlFunction pg_stat_get_db_blk_read_time cstring_send neqjoinsel position tsvectorin
syn keyword sqlFunction array_ndims hashchar int84gt textne range_contains textsend mic_to_euc_kr
syn keyword sqlFunction float8_regr_syy int4ge int24mi array_position xml_is_well_formed_content
syn keyword sqlFunction int2mul _pg_char_max_length regproceduresend isclosed
syn keyword sqlFunction pg_stat_get_numscans regprocrecv point_left gist_box_fetch icnlikesel
syn keyword sqlFunction float8send lseg_out float8up upper_inc hashbpchar pg_lock_status varbitgt
syn keyword sqlFunction cash_send xml_is_well_formed_document array_agg bit_out date_lt lower_inc
syn keyword sqlFunction tsquery_and float8_corr utf8_to_euc_cn concat pg_get_functiondef
syn keyword sqlFunction json_extract_path smgrne smgrin pg_stat_get_db_temp_files int24le
syn keyword sqlFunction bound_box bit_and macaddr_gt brinendscan regexnejoinsel record_image_ne
syn keyword sqlFunction byteale pg_create_logical_replication_slot diagonal euc_kr_to_mic
syn keyword sqlFunction johab_to_utf8 int48pl pg_ts_dict_is_visible tsquery_ge network
syn keyword sqlFunction txid_snapshot_xmax poly_contain_pt spg_range_quad_leaf_consistent
syn keyword sqlFunction bpchar_pattern_lt xidrecv lower sjis_to_mic cash_cmp enum_in
syn keyword sqlFunction ginqueryarrayextract pg_start_backup overlay pg_get_expr float4div circle
syn keyword sqlFunction pg_database_size json_strip_nulls int4recv ginbuildempty
syn keyword sqlFunction date_ne_timestamptz bpcharrecv pg_get_function_identity_arguments
syn keyword sqlFunction pg_stat_get_tuples_deleted abstimelt btbeginscan hashint2 iso8859_to_utf8
syn keyword sqlFunction timezone varcharsend to_jsonb substr timetz_send numeric_recv int48mul
syn keyword sqlFunction intinterval lseg_lt tsvector_ge timestamptz_gt_timestamp cash_div_int4
syn keyword sqlFunction abstimege btoidsortsupport text_gt gincostestimate dpow json_object_keys
syn keyword sqlFunction pg_stat_get_db_blocks_hit ginrescan gistrescan int8pl_inet
syn keyword sqlFunction date_le_timestamp charlt pg_stat_get_bgwriter_timed_checkpoints boolrecv
syn keyword sqlFunction spg_kd_inner_consistent var_pop regtypesend txid_visible_in_snapshot
syn keyword sqlFunction booland_statefunc range_gist_penalty pg_replication_origin_drop
syn keyword sqlFunction regnamespaceout statement_timestamp int2_sum enum_ne latin2_to_mic
syn keyword sqlFunction circle_distance macaddr_eq numeric_var_pop covar_samp
syn keyword sqlFunction gin_consistent_jsonb reltimeeq regconfigsend ltrim float8out interval_le
syn keyword sqlFunction path_send pg_stat_get_xact_tuples_updated charsend line_interpt tideq
syn keyword sqlFunction row_security_active ginbulkdelete hashbulkdelete daterange_subdiff
syn keyword sqlFunction numrange_subdiff win1251_to_iso btabstimecmp inter_sl querytree
syn keyword sqlFunction float8_var_pop enum_recv gtsquery_union box_overabove oidvectorne
syn keyword sqlFunction prsd_headline pg_stat_get_bgwriter_maxwritten_clean bool_and
syn keyword sqlFunction inet_gist_compress min network_ge dsynonym_init plpgsql_inline_handler
syn keyword sqlFunction varbit_in strpos int24pl tinterval _pg_char_octet_length namelike
syn keyword sqlFunction varbittypmodout jsonb_to_record anynonarray_out close_sl oidout
syn keyword sqlFunction pg_tablespace_databases timestamptz_cmp hashendscan aclitemeq json_typeof
syn keyword sqlFunction array_replace float8recv boollt reltime float8_accum array_fill
syn keyword sqlFunction gtsquery_compress poly_overright dist_ppath
syn keyword sqlFunction pg_stat_get_xact_tuples_fetched spginsert pg_lsn_send gtsvector_union
syn keyword sqlFunction float48pl float8abs numeric_fac current_schema int82div oidvectortypes
syn keyword sqlFunction corr ginarraytriconsistent timestamp_transform pg_get_serial_sequence
syn keyword sqlFunction gtsquery_consistent xml cashlarger pg_stat_get_xact_blocks_hit
syn keyword sqlFunction spg_range_quad_config hostmask obj_description cidout numeric_accum_inv
syn keyword sqlFunction timetz_lt spggettuple to_date date_trunc timestamptz_eq_date point_right
syn keyword sqlFunction point_above textrecv int84ne timestamptz_ge_date textin
syn keyword sqlFunction pg_stat_get_last_vacuum_time regoperout int8le varchartypmodin float8ne
syn keyword sqlFunction pg_stat_get_db_blocks_fetched log timetz_out json_in unknownsend
syn keyword sqlFunction timestamptz_cmp_timestamp chr masklen lo_truncate bit_send ts_lexize
syn keyword sqlFunction btint8sortsupport to_regnamespace pg_get_ruledef anyenum_out int42lt
syn keyword sqlFunction tsmatchjoinsel oidvectorle euc_tw_to_utf8 timestamp_zone_transform atan2
syn keyword sqlFunction bringetbitmap btint2cmp anyenum_in _pg_keysequal ts_debug
syn keyword sqlFunction pg_relation_size line_recv pg_encoding_to_char box_above_eq
syn keyword sqlFunction txid_snapshot_recv box_same network_sup oidrecv
syn keyword sqlFunction pg_stat_get_function_self_time int8up point_send int2not
syn keyword sqlFunction timestamp_gt_timestamptz btoptions iso_to_win1251 latin3_to_mic array_ne
syn keyword sqlFunction interval_pl_timestamptz int4smaller interval_pl_timetz arrayoverlap
syn keyword sqlFunction btint8cmp utf8_to_shift_jis_2004 byteagt md5 pg_try_advisory_xact_lock
syn keyword sqlFunction gtsvector_same anyarray_in koi8r_to_win866 ishorizontal covar_pop
syn keyword sqlFunction percentile_cont lseg_ge latin1_to_mic timestamptz_recv dense_rank_final
syn keyword sqlFunction timeofday pg_ls_dir jsonb_array_element_text lseg_center lseg variance
syn keyword sqlFunction dense_rank ceiling int4div pg_stat_get_bgwriter_buf_written_clean
syn keyword sqlFunction inet_gist_penalty int8inc_float8_float8 initcap bpcharnlike mic_to_euc_cn
syn keyword sqlFunction bernoulli anyrange_out namene time_eq pg_stat_get_backend_activity_start
syn keyword sqlFunction bttintervalcmp gin_extract_tsvector float8smaller win866_to_win1251
syn keyword sqlFunction int84eq jsonb_in path_sub_pt btint4cmp btint2sortsupport box_distance
syn keyword sqlFunction timestamp_ne_date reltimegt json_populate_recordset isopen first_value
syn keyword sqlFunction json_object_agg decode regclassout numerictypmodout pg_ddl_command_send
syn keyword sqlFunction array_dims circle_send pg_replication_origin_advance justify_interval
syn keyword sqlFunction oidlt int4mi tintervalsend cume_dist_final timestamp_hash pg_column_size
syn keyword sqlFunction query_to_xmlschema interval_accum_inv circle_overbelow
syn keyword sqlFunction pg_stat_get_db_conflict_bufferpin bitge spg_quad_leaf_consistent
syn keyword sqlFunction upper_inf uuid_lt pg_lsn_eq int4le family timestamp_ne_timestamptz
syn keyword sqlFunction pg_stat_get_backend_client_addr box_intersect
syn keyword sqlFunction pg_logical_slot_peek_binary_changes table_to_xml spggetbitmap jsonb_le
syn keyword sqlFunction timestamptztypmodout abstimeout macaddr_le record_in ginendscan
syn keyword sqlFunction int2_accum_inv pg_sleep_for lseg_eq tsvectorsend int4_avg_accum diameter
syn keyword sqlFunction tidrecv RI_FKey_setnull_del tintervallengt radians regexp_matches dist_sl
syn keyword sqlFunction bpchar_pattern_ge tintervalrecv rtrim pg_is_in_backup pg_lsn_le
syn keyword sqlFunction to_regclass age RI_FKey_restrict_del pg_stat_get_backend_activity
syn keyword sqlFunction pg_event_trigger_ddl_commands brinbuildempty poly_overleft
syn keyword sqlFunction percentile_disc_multi_final flt4_mul_cash uuid_ne interval_pl_timestamp
syn keyword sqlFunction float8in mod int8recv pg_prepared_xact row_to_json date_cmp_timestamptz
syn keyword sqlFunction array_length inet_gist_fetch date_in int2_avg_accum_inv
syn keyword sqlFunction pg_extension_config_dump abstimene oidsend eqjoinsel array_lower
syn keyword sqlFunction pg_stat_get_db_tuples_inserted current_query numeric_poly_var_samp cos
syn keyword sqlFunction numeric_le jsonb_populate_record now reltimein timestamp_send avg
syn keyword sqlFunction array_le to_regoper pg_create_physical_replication_slot uuid_send
syn keyword sqlFunction btfloat4cmp RI_FKey_cascade_upd circle_le pow
syn keyword sqlFunction pg_stat_get_db_tuples_updated has_language_privilege
syn keyword sqlFunction pg_show_all_file_settings cstring_in pg_prepared_statement
syn keyword sqlFunction pg_get_function_result interval_div hashmacaddr circle_mul_pt
syn keyword sqlFunction dispell_lexize percent_rank cash_eq bitnot date_eq_timestamp
syn keyword sqlFunction record_image_eq RI_FKey_setdefault_del close_ps dist_sb
syn keyword sqlFunction pg_event_trigger_dropped_objects contjoinsel regr_intercept
syn keyword sqlFunction line_intersect mic_to_ascii generate_series numeric_transform
syn keyword sqlFunction mic_to_win1251 range_lt regdictionaryin mic_to_iso interval_recv
syn keyword sqlFunction pg_stat_get_wal_senders reltimene pg_event_trigger_table_rewrite_reason
syn keyword sqlFunction varbitne btfloat48cmp int2_mul_cash bpcharsend regdictionaryout
syn keyword sqlFunction pg_logical_slot_get_changes tintervalout int8or int84mi varbitle
syn keyword sqlFunction lo_export intervaltypmodin range_gt pg_stat_get_db_xact_rollback int8
syn keyword sqlFunction date cash_recv textlen pg_stat_get_xact_numscans interval_eq hashfloat8
syn keyword sqlFunction timestamptz_ne utf8_to_euc_jis_2004 plpgsql_call_handler jsonb_typeof
syn keyword sqlFunction pg_get_indexdef boolout ts_match_qv tsquery_lt cash_mi database_to_xml
syn keyword sqlFunction circle_overlap binary_upgrade_set_next_toast_pg_class_oid ceil texticlike
syn keyword sqlFunction RI_FKey_noaction_upd timestamptz_ne_date date_eq hashcostestimate
syn keyword sqlFunction pg_lsn_gt line dist_cpoly array_lt tsvector_le win_to_utf8 int82pl
syn keyword sqlFunction timetz_le int4lt string_agg_finalfn cash_div_flt4 numeric_var_samp
syn keyword sqlFunction int28ne circle_overleft plainto_tsquery point_out tidne max
syn keyword sqlFunction dsynonym_lexize neqsel dtrunc tintervalin int2vectorsend regnamespacesend
syn keyword sqlFunction int2smaller array_smaller line_in int8out center jsonb_pretty btint84cmp
syn keyword sqlFunction varbitcmp gin_consistent_jsonb_path spg_text_leaf_consistent
syn keyword sqlFunction jsonb_delete_path bit_in charin pg_cursor date_lt_timestamptz timetz_hash
syn keyword sqlFunction pg_lsn_cmp numeric_uplus float48eq int2recv aclinsert utf8_to_iso8859_1
syn keyword sqlFunction pg_replication_origin_oid jsonb_object_agg_finalfn lo_create void_send
syn keyword sqlFunction int48div interval event_trigger_in nlikesel int28le path_div_pt like
syn keyword sqlFunction enum_first array_agg_array_transfn pg_timezone_names pg_my_temp_schema
syn keyword sqlFunction poly_overbelow win1250_to_latin2 float8_avg fmgr_sql_validator date_pli
syn keyword sqlFunction make_timestamp _pg_truetypid pg_relation_filenode int4eq cash_mul_flt4
syn keyword sqlFunction oidle int24eq euc_cn_to_mic tsqueryrecv record_image_gt oidvectorgt
syn keyword sqlFunction time_larger void_out array_append to_regrole
syn keyword sqlFunction pg_stat_get_db_blk_write_time pg_is_other_temp_schema ginrestrpos
syn keyword sqlFunction RI_FKey_cascade_del tsquery_eq int8dec pg_identify_object pg_switch_xlog
syn keyword sqlFunction timestamp_sortsupport regrolerecv cot pg_stat_get_xact_tuples_returned
syn keyword sqlFunction range_gist_fetch likejoinsel event_trigger_out koi8u_to_utf8 circle_gt
syn keyword sqlFunction byteacmp float4mul split_part left range_intersect int8range
syn keyword sqlFunction json_array_element koi8r_to_iso path_distance int82ne big5_to_utf8
syn keyword sqlFunction pg_advisory_xact_lock_shared pg_stat_reset float4gt
syn keyword sqlFunction binary_upgrade_set_next_pg_authid_oid numeric_ln
syn keyword sqlFunction tsvector_update_trigger_column enum_gt spgmarkpos hashtext circle_ne
syn keyword sqlFunction bitgt int2vectoreq network_le abstimein xidin json_out
syn keyword sqlFunction shift_jis_2004_to_utf8 timestamp_smaller gist_poly_consistent int82mi
syn keyword sqlFunction numeric_sqrt domain_in lo_close range_typanalyze tintervalend spgrescan
syn keyword sqlFunction hashint8 float8_covar_pop timetz_gt cash_pl int2 gist_box_consistent
syn keyword sqlFunction time_hash pg_identify_object_as_address namegt xideqint4 pg_indexes_size
syn keyword sqlFunction varbit_send varchar date_lt_timestamp int2ge int2mod
syn keyword sqlFunction pg_get_function_arg_default brininsert numeric_abs regoperin
syn keyword sqlFunction gtsquery_decompress jsonb_out pg_replication_origin_session_setup
syn keyword sqlFunction pg_node_tree_send numrange regr_avgx pg_node_tree_out
syn keyword sqlFunction shift_jis_2004_to_euc_jis_2004 gistinsert numeric_out date_pl_interval
syn keyword sqlFunction lseg_in tsrange_subdiff point_div byteaout hashvarlena aclexplode
syn keyword sqlFunction arraycontains win1251_to_win866 inet_server_addr btrecordcmp macaddr_cmp
syn keyword sqlFunction jsonb_eq lo_lseek tidgt timestamp_out jsonb_to_recordset json_agg_finalfn
syn keyword sqlFunction network_overlap int8inc numeric_exp jsonb_build_array
syn keyword sqlFunction jsonb_populate_recordset binary_upgrade_create_empty_extension btendscan
syn keyword sqlFunction pg_stat_get_autoanalyze_count enum_send btvacuumcleanup
syn keyword sqlFunction percentile_cont_interval_final to_hex uuid_ge oidvectorrecv current_user
syn keyword sqlFunction box_add atan internal_out void_recv record_eq regprocsend on_ps array_in
syn keyword sqlFunction tintervalov timetz_in ginarrayconsistent btoidcmp tintervalstart
syn keyword sqlFunction tsq_mcontains int8mul pg_current_xlog_insert_location
syn keyword sqlFunction range_gist_picksplit bool_accum_inv charne pg_encoding_max_length byteain
syn keyword sqlFunction btgettuple poly_out record_lt row_number aclitemout int8gt jsonb_ne
syn keyword sqlFunction currval int4shr bittypmodin inet_gist_union numeric_power
syn keyword sqlFunction txid_current_snapshot date_gt_timestamptz record_image_le
syn keyword sqlFunction pg_collation_is_visible pg_sequence_parameters
syn keyword sqlFunction pg_stat_get_db_stat_reset_time convert range_gist_compress float4abs
syn keyword sqlFunction to_char textanycat cume_dist jsonb_object_agg utf8_to_euc_jp get_byte
syn keyword sqlFunction cash_lt numeric_uminus namesend ts_headline lowrite
syn keyword sqlFunction pg_tablespace_location int2lt float8_regr_sxx json_object_agg_finalfn
syn keyword sqlFunction int4in euc_jis_2004_to_utf8 point_mul numeric_poly_stddev_samp box_in
syn keyword sqlFunction tsquerysend justify_hours thesaurus_lexize money language_handler_in
syn keyword sqlFunction bpcharin timetz_recv int48lt euc_jp_to_mic any_out bool_or float84mi
syn keyword sqlFunction int24div int8dec_any enum_larger time_smaller box_right aclremove
syn keyword sqlFunction uuid_cmp macaddr_or hashoptions float4lt network_eq
syn keyword sqlFunction timestamptz_ne_timestamp RI_FKey_check_upd spgcanreturn cash_div_int2
syn keyword sqlFunction ts_rank lo_get lseg_intersect int42div gin_cmp_prefix timetz_ne
syn keyword sqlFunction arraycontjoinsel bttextsortsupport btfloat8sortsupport
syn keyword sqlFunction numeric_sortsupport numeric_poly_stddev_pop utf8_to_iso8859 float4larger
syn keyword sqlFunction jsonb_exists_any regoperrecv box_sub gist_box_union timetztypmodin
syn keyword sqlFunction gininsert bpcharle pg_reload_conf div pg_advisory_lock_shared oidgt
syn keyword sqlFunction height circle_lt pg_logical_slot_peek_changes pg_stat_reset_shared timetz
syn keyword sqlFunction jsonb_array_element currtid pg_stat_get_dead_tuples btinsert polygon
syn keyword sqlFunction dlog10 opaque_out oidvectorlt int8and justify_days pg_lsn_recv stddev_pop
syn keyword sqlFunction count format box_below_eq int4range_canonical float84ne pg_is_in_recovery
syn keyword sqlFunction int4_accum cash_mul_flt8 timemi int4_accum_inv stddev_samp timestamptz_eq
syn keyword sqlFunction exp time_lt gist_box_decompress hash_numeric
syn keyword sqlFunction pg_logical_slot_get_binary_changes contsel int2abs timetz_larger
syn keyword sqlFunction varcharout jsonb_extract_path json_array_length acldefault path_npoints
syn keyword sqlFunction brinoptions path_n_lt interval_hash hashint2vector lseg_vertical
syn keyword sqlFunction interval_transform bpcharregexeq database_to_xml_and_xmlschema path_inter
syn keyword sqlFunction date_le circle_overabove lo_tell64 array_agg_array_finalfn bpchareq
syn keyword sqlFunction tintervaleq pg_event_trigger_table_rewrite_oid byteaeq btrestrpos
syn keyword sqlFunction dist_polyp circle_contained generate_subscripts gistbeginscan cardinality
syn keyword sqlFunction ginoptions jsonb_contains translate float8_stddev_samp numeric_sum
syn keyword sqlFunction spgrestrpos interval_mi lpad array_gt getpgusername regoperatorrecv
syn keyword sqlFunction pg_xact_commit_timestamp xideq poly_contained
syn keyword sqlFunction pg_stat_get_backend_client_port record_ne win1251_to_koi8r
syn keyword sqlFunction varchar_transform json_agg_transfn set_bit poly_below dist_lb to_regproc
syn keyword sqlFunction euc_jis_2004_to_shift_jis_2004 enum_lt interval_smaller oideq
syn keyword sqlFunction numeric_larger gist_poly_compress json_array_elements json_agg
syn keyword sqlFunction text_larger pg_get_multixact_members lseg_length txid_snapshot_in
syn keyword sqlFunction spg_text_choose range_overleft nextval pg_lsn_in nth_value oidvectorge
syn keyword sqlFunction lo_tell array_eq varbit_out range_gist_union float8lt lo_truncate64
syn keyword sqlFunction array_upper inet_send tintervallenlt timestamp_lt_date euc_jp_to_utf8
syn keyword sqlFunction replace byteasend pg_postmaster_start_time json_send timestamptz_le_date
syn keyword sqlFunction lo_open has_tablespace_privilege float4ne range_recv dlog1 trigger_in
syn keyword sqlFunction macaddr_recv xmlconcat2 varchartypmodout gin_extract_tsquery
syn keyword sqlFunction timestamp_eq_date uuid_le path_n_le ordered_set_transition
syn keyword sqlFunction float8_stddev_pop text_pattern_ge int2um regoperatorsend
syn keyword sqlFunction getdatabaseencoding mic_to_euc_tw float8_regr_accum utf8_to_win
syn keyword sqlFunction gist_box_penalty jsonb_build_object spgbulkdelete array_to_string
syn keyword sqlFunction pg_table_is_visible anyarray_recv circle_out ts_rank_cd _pg_interval_type
syn keyword sqlFunction bitcmp length numeric_avg int4_sum timestamptz_smaller int4shl
syn keyword sqlFunction btfloat84cmp fdw_handler_in int4mul hashbuildempty hashinet numeric_inc
syn keyword sqlFunction txid_snapshot_xip circle_contain_pt pg_timezone_abbrevs btint48cmp
syn keyword sqlFunction json_extract_path_text utf8_to_gbk timestamp_cmp dexp abstimele
syn keyword sqlFunction bpcharregexne time_transform bpcharne regconfigin
syn keyword sqlFunction pg_stat_get_backend_start timestamp_in hashrescan pg_opfamily_is_visible
syn keyword sqlFunction gist_point_distance float84gt ts_typanalyze array_agg_finalfn makeaclitem
syn keyword sqlFunction time_cmp pg_stat_file current_setting pg_conversion_is_visible namege
syn keyword sqlFunction on_sl int48gt int8_avg regprocedurein dsimple_init pg_lsn_out
syn keyword sqlFunction brin_inclusion_opcinfo gistgettuple interval_um euc_kr_to_utf8 date_cmp
syn keyword sqlFunction float8_regr_slope gtsquery_penalty iso_to_koi8r int4 bpchariclike
syn keyword sqlFunction to_regoperator gtsvector_compress json_array_element_text
syn keyword sqlFunction int8range_subdiff float4le path_mul_pt xidout int2div time_ne
syn keyword sqlFunction pg_stat_get_tuples_returned numeric_cmp gin_cmp_tslexeme
syn keyword sqlFunction tsvector_update_trigger regtypeout circle_in jsonb_send range_adjacent
syn keyword sqlFunction bttext_pattern_cmp thesaurus_init to_regprocedure
syn keyword sqlFunction pg_available_extension_versions close_pb cash_gt spg_kd_config path_n_gt
syn keyword sqlFunction line_parallel range_ge slope float8_regr_r2 jsonb_array_elements inet_in
syn keyword sqlFunction record_out range_ne path_center point_horiz table_to_xmlschema
syn keyword sqlFunction timestamp_le_timestamptz int4range overlaps pg_advisory_unlock
syn keyword sqlFunction box_contain_pt int4send hash_range timestamptztypmodin hashname int42mi
syn keyword sqlFunction float84le boolor_statefunc text_ge bpcharlt int84ge
syn keyword sqlFunction pg_stat_get_vacuum_count currtid2 daterange utf8_to_euc_tw
syn keyword sqlFunction line_horizontal int28eq int8ne path_add_pt integer_pl_date cash_ne
syn keyword sqlFunction pg_stat_get_function_total_time timestamptz_mi_interval pg_lsn_mi box_le
syn keyword sqlFunction json_build_array btint24cmp range_merge bool int28lt btnamesortsupport
syn keyword sqlFunction int2vectorrecv bitcat oidvectoreq regnamespacerecv gist_box_picksplit
syn keyword sqlFunction RI_FKey_restrict_upd jsonb_exists_all lo_unlink setseed
syn keyword sqlFunction has_foreign_data_wrapper_privilege int8abs int82gt macaddr_send
syn keyword sqlFunction pg_stat_get_xact_tuples_inserted tintervalgt tsq_mcontained
syn keyword sqlFunction json_build_object circle_above xpath pg_stat_clear_snapshot width pclose
syn keyword sqlFunction int4gt int82eq spgbeginscan tintervallenge int42pl anyelement_out
syn keyword sqlFunction percentile_disc _pg_numeric_scale range_after numeric_stddev_samp
syn keyword sqlFunction gbk_to_utf8 win1251_to_mic mic_to_sjis box_mul btfloat4sortsupport
syn keyword sqlFunction substring box_below mic_to_big5 regr_sxx abstime tidlarger charle dist_pb
syn keyword sqlFunction pg_replication_origin_session_progress float4 int48mi
syn keyword sqlFunction gin_tsquery_triconsistent timestamp_mi date_out inet_gist_decompress
syn keyword sqlFunction float48mi anyelement_in hashbeginscan range_contained_by jsonb_cmp
syn keyword sqlFunction timetzdate_pl timestamp_pl_interval btcanreturn clock_timestamp nameeq
syn keyword sqlFunction numeric_ne tsquery_not jsonb_each_text regopersend timestamptz_mi
syn keyword sqlFunction varbittypmodin timetz_smaller regclass pg_stat_get_archiver pg_sleep
syn keyword sqlFunction pg_ddl_command_out anyrange_in macaddr_in tsqueryout int2vectorin
syn keyword sqlFunction int4_avg_accum_inv tsvector_eq xml_in close_ls float84pl
syn keyword sqlFunction shobj_description bool_anytrue brinrestrpos trunc reltimeout int28pl
syn keyword sqlFunction timestamptz_lt_date tsquery_le reverse circle_add_pt tsquery_gt
syn keyword sqlFunction time_mi_time schema_to_xml float84eq interval_ge notlike lseg_recv
syn keyword sqlFunction xpath_exists inet_client_addr pg_ts_parser_is_visible poly_recv
syn keyword sqlFunction query_to_xml boolle regexeqjoinsel tidge pg_advisory_unlock_shared
syn keyword sqlFunction timestamp_ge_timestamptz brinbeginscan int48le
syn keyword sqlFunction pg_stat_get_db_tuples_deleted pg_stat_get_db_conflict_startup_deadlock
syn keyword sqlFunction cidin interval_send gistmarkpos euc_tw_to_big5 bpchartypmodout
syn keyword sqlFunction float8_regr_intercept interval_pl pg_get_triggerdef spg_quad_picksplit
syn keyword sqlFunction inter_lb date_recv text record_le jsonb_agg jsonb_object_field_text
syn keyword sqlFunction int28mi lastval timestamptypmodout

" PostGIS 2.2 functions
" To build this list use:
"
" psql template1
" create database tmp;
" \c tmp
" create schema postgis;
" create extension postgis with schema postgis;
" \t
" \o postgis_functions.txt
" select  distinct p.proname
" from    pg_catalog.pg_namespace n
" join    pg_catalog.pg_proc p
" on      p.pronamespace = n.oid
" where   n.nspname = 'postgis';
"
" Remove _* functions before pasting into this file.
syn keyword sqlFunction geometry_overbelow geography_gist_distance st_seteffectivearea
syn keyword sqlFunction st_line_substring st_numpatches st_linetocurve geometry_below
syn keyword sqlFunction st_summarystats st_approxquantile st_makevalid st_extent
syn keyword sqlFunction geography_gist_consistent postgis_geos_version st_roughness
syn keyword sqlFunction postgis_lib_version st_rotate pgis_geometry_union_finalfn
syn keyword sqlFunction st_locate_along_measure geography_distance_knn st_segmentize
syn keyword sqlFunction st_pointfromtext st_numpoints st_endpoint pgis_geometry_accum_finalfn
syn keyword sqlFunction st_shift_longitude st_scaley st_pixelofvalue st_width st_azimuth
syn keyword sqlFunction st_mindist4ma st_linemerge st_geometryfromtext st_tpi st_wkbtosql
syn keyword sqlFunction postgis_lib_build_date st_addmeasure st_removepoint st_zmax
syn keyword sqlFunction st_3ddfullywithin bytea postgis_dropbbox st_interpolatepoint raster_hash
syn keyword sqlFunction st_find_extent st_zmin st_asgeojson st_nearestvalue st_makepoint
syn keyword sqlFunction st_length2dspheroid st_skewy st_perimeter2d st_linestringfromwkb
syn keyword sqlFunction st_box2dfromgeohash st_mpointfromwkb st_geomcollfromtext st_clusterwithin
syn keyword sqlFunction st_hillshade st_invdistweight4ma st_isvalidreason st_geogfromtext
syn keyword sqlFunction postgis_raster_lib_build_date st_force_collection st_node
syn keyword sqlFunction st_isvalidtrajectory st_force_3d geography_gt st_rescale st_bandpixeltype
syn keyword sqlFunction st_sharedpaths st_astext st_dump st_locate_between_measures st_y
syn keyword sqlFunction st_snaptogrid st_linefromencodedpolyline geometry_left
syn keyword sqlFunction st_linefrommultipoint raster_contained st_covers st_combine_bbox
syn keyword sqlFunction st_locatebetween geometry_gist_penalty_2d pgis_geometry_collect_finalfn
syn keyword sqlFunction box2df_in st_bandmetadata st_force_4d st_makepointm
syn keyword sqlFunction st_linecrossingdirection st_3dclosestpoint postgis_constraint_type
syn keyword sqlFunction st_makebox2d st_offsetcurve st_pixelwidth st_centroid postgis_type_name
syn keyword sqlFunction box3d postgis_hasbbox st_value postgis_scripts_released
syn keyword sqlFunction st_pixelascentroids st_area st_forcesfs geometry_right st_contains
syn keyword sqlFunction st_dwithin st_rotation postgis_getbbox st_coveredby st_multi
syn keyword sqlFunction st_setupperleft st_memunion geography_out st_astiff
syn keyword sqlFunction st_rastertoworldcoordy st_concavehull st_setpoint st_worldtorastercoord
syn keyword sqlFunction st_summarystatsagg st_dfullywithin raster_contained_by_geometry
syn keyword sqlFunction geometry_overleft populate_geometry_columns st_mpointfromtext
syn keyword sqlFunction st_isvaliddetail st_geomfromwkb st_polygon st_rotatey geography_send
syn keyword sqlFunction longtransactionsenabled st_closestpointofapproach st_lineinterpolatepoint
syn keyword sqlFunction st_line_interpolate_point st_wkttosql geometry_typmod_in
syn keyword sqlFunction geography_typmod_in enablelongtransactions st_project st_asgml
syn keyword sqlFunction st_issimple geometry_recv geometry_contained_by_raster st_bdmpolyfromtext
syn keyword sqlFunction geometry_gist_distance_2d st_boundary st_pointinsidecircle st_resample
syn keyword sqlFunction st_interiorringn checkauth polygon st_force4d st_locatealong geometrytype
syn keyword sqlFunction postgis_typmod_type st_force3dm st_multilinestringfromtext path
syn keyword sqlFunction st_coorddim st_rotatez dropgeometrycolumn st_hausdorffdistance
syn keyword sqlFunction geometry_le postgis_transform_geometry st_longestline
syn keyword sqlFunction geometry_gist_distance_nd st_area2d st_bandnodatavalue st_distancecpa
syn keyword sqlFunction st_geomfromgeojson st_neighborhood geometry_overabove
syn keyword sqlFunction geometry_gist_compress_2d st_hasarc updaterastersrid
syn keyword sqlFunction st_symmetricdifference st_length2d st_shortestline st_quantile gidx_out
syn keyword sqlFunction st_affine geography_in st_geographyfromtext geometry_send st_simplifyvw
syn keyword sqlFunction postgis_raster_lib_version raster_overlap st_mapalgebraexpr
syn keyword sqlFunction geometry_overright st_bdpolyfromtext pgis_geometry_clusterwithin_finalfn
syn keyword sqlFunction st_pointfromgeohash gserialized_gist_joinsel_2d st_polygonfromwkb
syn keyword sqlFunction st_cleangeometry st_mpolyfromwkb geometry_raster_contain
syn keyword sqlFunction st_notsamealignmentreason geometry_overlaps_nd geometry postgis_addbbox
syn keyword sqlFunction st_force_3dm geometry_same st_resize st_memcollect st_numinteriorring
syn keyword sqlFunction raster_overabove get_proj4_from_srid st_transform st_estimatedextent
syn keyword sqlFunction st_pixelaspoint st_ashexewkb geography_analyze st_pointn
syn keyword sqlFunction st_distancesphere st_makeline box3d_out postgis_svn_version st_equals
syn keyword sqlFunction st_patchn st_upperleftx st_length st_geomfromgml st_metadata st_srid
syn keyword sqlFunction st_3dlength geometry_gist_picksplit_2d st_mpolyfromtext raster_above
syn keyword sqlFunction st_mem_size st_rotatex st_height st_numbands st_asgdalraster st_subdivide
syn keyword sqlFunction pgis_geometry_polygonize_finalfn st_reclass geomfromewkt
syn keyword sqlFunction st_point_inside_circle geometry_gist_compress_nd st_worldtorastercoordy
syn keyword sqlFunction st_geotransform st_assvg box2d_out st_setgeoreference raster_below
syn keyword sqlFunction st_summary st_multilinefromwkb st_setbandnodatavalue
syn keyword sqlFunction geometry_gist_decompress_nd st_m geometry_lt st_combinebbox
syn keyword sqlFunction geography_typmod_out st_geomfromewkt st_convexhull raster_contain
syn keyword sqlFunction st_mlinefromtext geometry_contains dropoverviewconstraints geography_le
syn keyword sqlFunction dropgeometrytable geometry_distance_centroid_nd geometry_typmod_out
syn keyword sqlFunction st_symdifference box2df_out geography_recv raster_in st_z st_force3dz
syn keyword sqlFunction raster_right geometry_in st_distinct4ma geometry_gist_union_2d st_relate
syn keyword sqlFunction st_numgeometries disablelongtransactions raster_eq st_unaryunion
syn keyword sqlFunction st_polyfromwkb st_xmax st_touches st_geomfromgeohash box3d_in st_envelope
syn keyword sqlFunction geography_ge postgis_gdal_version postgis_libjson_version st_asjpeg
syn keyword sqlFunction postgis_typmod_dims st_aspng raster_geometry_overlap equals st_3ddistance
syn keyword sqlFunction st_maxdistance st_containsproperly st_mapalgebrafctngb st_upperlefty
syn keyword sqlFunction st_createoverview st_asewkb gserialized_gist_joinsel_nd
syn keyword sqlFunction st_3dlength_spheroid raster_overright spheroid_in st_zmflag
syn keyword sqlFunction postgis_version st_dumpaspolygons raster_geometry_contain
syn keyword sqlFunction postgis_proj_version st_multipointfromtext st_scalex st_linelocatepoint
syn keyword sqlFunction geometry_gt st_boundingdiagonal st_geomfromkml geometry_gist_same_2d
syn keyword sqlFunction st_linefromtext geometry_ge st_dimension st_tile st_accum st_sum4ma
syn keyword sqlFunction geometry_within geometry_gist_union_nd st_multipolyfromwkb st_max4ma
syn keyword sqlFunction st_disjoint st_geohash st_3dlongestline geometry_above
syn keyword sqlFunction st_estimated_extent st_gdaldrivers st_ymax geometry_distance_cpa
syn keyword sqlFunction st_collectionhomogenize st_mean4ma st_simplifypreservetopology st_union
syn keyword sqlFunction find_srid spheroid_out st_flipcoordinates st_memsize box st_linefromwkb
syn keyword sqlFunction st_addband st_setgeotransform st_isclosed st_collect
syn keyword sqlFunction addoverviewconstraints postgis_constraint_dims geography_gist_penalty
syn keyword sqlFunction geography_eq st_intersection st_length_spheroid checkauthtrigger
syn keyword sqlFunction st_asraster st_point st_rastertoworldcoord st_distance st_findextent
syn keyword sqlFunction st_3dmaxdistance pgis_geometry_makeline_finalfn st_setvalue
syn keyword sqlFunction st_3dshortestline st_rastertoworldcoordx st_3dperimeter
syn keyword sqlFunction geometry_gist_same_nd postgis_typmod_srid st_curvetoline st_nrings
syn keyword sqlFunction st_linesubstring st_xmin st_3dmakebox geomfromewkb st_delaunaytriangles
syn keyword sqlFunction st_overlaps lockrow postgis_constraint_srid st_retile st_aslatlontext
syn keyword sqlFunction st_setrotation st_approxsummarystats unlockrows st_approxcount
syn keyword sqlFunction pgis_geometry_clusterintersecting_finalfn geometry_gist_penalty_nd
syn keyword sqlFunction st_expand st_histogram st_mapalgebra geometry_gist_consistent_2d gidx_in
syn keyword sqlFunction st_mapalgebrafct geometry_gist_consistent_nd postgis_noop
syn keyword sqlFunction st_lengthspheroid st_polygonfromtext st_addpoint updategeometrysrid
syn keyword sqlFunction st_difference st_bandpath pgis_abs_out st_isempty st_reverse st_3dextent
syn keyword sqlFunction st_skewx box2d_in st_slope st_removerepeatedpoints
syn keyword sqlFunction geometry_raster_overlap st_scale st_3ddwithin st_force_2d st_hasnoband
syn keyword sqlFunction st_geomcollfromwkb st_dumppoints st_x raster_overbelow st_forcerhr
syn keyword sqlFunction postgis_full_version postgis_cache_bbox st_minconvexhull st_ymin
syn keyword sqlFunction st_asbinary st_cpawithin st_multipointfromwkb st_buffer
syn keyword sqlFunction st_multipolygonfromtext gettransactionid raster_same st_astwkb
syn keyword sqlFunction geography_gist_picksplit st_valuepercent addgeometrycolumn
syn keyword sqlFunction st_closestpoint st_reskew st_orderingequals st_force3d point
syn keyword sqlFunction gserialized_gist_sel_nd geometry_overlaps gserialized_gist_sel_2d
syn keyword sqlFunction st_distance_sphere st_npoints st_isring st_exteriorring
syn keyword sqlFunction st_collectionextract st_minimumboundingcircle st_iscoveragetile
syn keyword sqlFunction st_distancespheroid geography_gist_compress st_bandisnodata st_setscale
syn keyword sqlFunction st_worldtorastercoordx st_shiftlongitude geography_overlaps st_polygonize
syn keyword sqlFunction st_intersects st_polyfromtext st_geomfromtwkb postgis_libxml_version
syn keyword sqlFunction st_geogfromwkb postgis_scripts_installed st_setbandisnodata
syn keyword sqlFunction st_swapordinates st_clipbybox2d pgis_geometry_accum_transfn st_perimeter
syn keyword sqlFunction droprasterconstraints geometry_gist_picksplit_nd st_iscollection
syn keyword sqlFunction addrasterconstraints st_within box2d st_range4ma geometry_out
syn keyword sqlFunction geometry_cmp st_clusterintersecting st_pixelaspolygon st_snap st_asewkt
syn keyword sqlFunction st_asx3d st_translate geography_cmp st_valuecount st_aspect geometry_eq
syn keyword sqlFunction st_line_locate_point st_geomfromewkb st_ndims st_makeemptyraster
syn keyword sqlFunction st_pointonsurface st_min4ma st_pixelheight st_forcecurve st_makepolygon
syn keyword sqlFunction st_stddev4ma postgis_scripts_build_date geography_lt geometry_analyze
syn keyword sqlFunction raster_left st_gmltosql st_length2d_spheroid st_geomfromtext
syn keyword sqlFunction geometry_distance_centroid st_pixelascentroid st_mlinefromwkb
syn keyword sqlFunction raster_overleft st_numinteriorrings st_transscale st_relatematch
syn keyword sqlFunction st_colormap st_count st_minpossiblevalue st_asencodedpolyline
syn keyword sqlFunction st_startpoint st_georeference st_isvalid geography_gist_union st_crosses
syn keyword sqlFunction geometry_distance_box st_force_3dz st_approxhistogram
syn keyword sqlFunction postgis_liblwgeom_version addauth st_locatebetweenelevations box3dtobox
syn keyword sqlFunction st_fromgdalraster st_askml st_setvalues geography_gist_same st_dumpvalues
syn keyword sqlFunction st_setskew st_pixelaspoints st_samealignment pgis_abs_in st_force2d
syn keyword sqlFunction st_3dintersects st_geometrytype st_buildarea st_pointfromwkb
syn keyword sqlFunction postgis_raster_scripts_installed raster_out st_simplify st_split
syn keyword sqlFunction st_geometryn st_setsrid st_band st_makeenvelope st_dumprings
syn keyword sqlFunction st_distance_spheroid geography st_clip st_forcecollection text
syn keyword sqlFunction geography_gist_decompress geometry_gist_decompress_2d st_countagg st_tri
syn keyword sqlFunction st_pixelaspolygons

syn keyword sqlOperator  all and any between distinct escape except exists
syn keyword sqlOperator  ilike in intersect like not or like_regex similar
syn keyword sqlOperator  some to union

syn keyword sqlStatement alter analyze comment commit copy create delete drop
syn keyword sqlStatement execute explain grant insert lock revoke rollback
syn keyword sqlStatement savepoint select set truncate update

" To build this list:
"
" psql template1
" \t
" \o types.txt
" select distinct pg_catalog.format_type(t.oid, null) as "name"
"   from pg_catalog.pg_type t
"   left join pg_catalog.pg_namespace n
"     on n.oid = t.typnamespace
"  where (t.typrelid = 0 or (select c.relkind = 'c' from pg_catalog.pg_class c
"                             where c.oid = t.typrelid))
"    and not exists(select 1 from pg_catalog.pg_type el
"                    where el.oid = t.typelem and el.typarray = t.oid)
"    and pg_catalog.pg_type_is_visible(t.oid)
"  order by "name";
"
"  Note that there are data type names composed of more than one word and
"  some other are between quotes. The list must be complemented with the
"  types and aliases listed in Table 8-1 of PostgreSQL manual.
syn keyword sqlType abstime aclitem any anyarray anyelement anyenum anynonarray anyrange
syn keyword sqlType bigint bigserial bit boolean box bytea char character varying cid cidr
syn keyword sqlType circle cstring date daterange decimal double precision event_trigger
syn keyword sqlType fdw_handler float4 float8 gtsvector inet int int2 int2vector int4
syn keyword sqlType int4range int8 int8range integer internal interval json jsonb
syn keyword sqlType language_handler line lseg macaddr money name numeric numrange oid
syn keyword sqlType oidvector opaque path pg_ddl_command pg_lsn pg_node_tree point polygon
syn keyword sqlType real record refcursor regclass regconfig regdictionary regnamespace
syn keyword sqlType regoper regoperator regproc regprocedure regrole regtype reltime serial
syn keyword sqlType serial2 serial4 serial8 smallint smallserial smgr text tid time with time
syn keyword sqlType zone time without timestamp timestampz timetz tinterval trigger
syn keyword sqlType tsm_handler tsquery tsrange tstzrange tsvector txid_snapshot unknown uuid
syn keyword sqlType varbit varchar void xid xml

" PostGIS 2.2 types
" From pg_type and PostGIS manual
syn keyword sqlType addbandarg agg_count agg_samealignment box2d box2df box3d geography
syn keyword sqlType geometry geomtry_dump geomval gidx pgis_abs rastbandarg raster reclassarg
syn keyword sqlType spheroid summarystats unionarg valid_detail

" Constants
syn keyword sqlConstant  debug5 debug4 debug3 debug2 debug1 log notice warning
syn keyword sqlConstant  error fatal panic
" System catalogs:
syn keyword sqlConstant  pg_aggregate pg_am pg_amop pg_amproc pg_attrdef
syn keyword sqlConstant  pg_attribute pg_auth_members pg_authid
syn keyword sqlConstant  pg_available_extension_versions
syn keyword sqlConstant  pg_available_extensions pg_cast pg_class
syn keyword sqlConstant  pg_collation pg_constraint pg_conversion pg_cursors
syn keyword sqlConstant  pg_database pg_db_role_setting pg_default_acl
syn keyword sqlConstant  pg_depend pg_description pg_enum pg_event_trigger
syn keyword sqlConstant  pg_extension pg_file_settings
syn keyword sqlConstant  pg_foreign_data_wrapper pg_foreign_server
syn keyword sqlConstant  pg_foreign_table pg_group pg_index pg_indexes
syn keyword sqlConstant  pg_inherits pg_language pg_largeobject
syn keyword sqlConstant  pg_largeobject_metadata pg_locks pg_matviews
syn keyword sqlConstant  pg_namespace pg_opclass pg_operator pg_opfamily
syn keyword sqlConstant  pg_pltemplate pg_policies pg_policy
syn keyword sqlConstant  pg_prepared_statements pg_prepared_xacts pg_proc
syn keyword sqlConstant  pg_range pg_replication_origin
syn keyword sqlConstant  pg_replication_origin_status pg_replication_slots
syn keyword sqlConstant  pg_rewrite pg_roles pg_rules pg_seclabel
syn keyword sqlConstant  pg_seclabels pg_settings pg_shadow pg_shdepend
syn keyword sqlConstant  pg_shdescription pg_shseclabel pg_statistic
syn keyword sqlConstant  pg_stats pg_tables pg_tablespace
syn keyword sqlConstant  pg_timezone_abbrevs pg_timezone_names pg_transform
syn keyword sqlConstant  pg_trigger pg_ts_config pg_ts_config_map pg_ts_dict
syn keyword sqlConstant  pg_ts_parser pg_ts_template pg_type pg_user
syn keyword sqlConstant  pg_user_mapping pg_user_mappings pg_views

" PostGIS 2.2 Grand Unified Custom Variables (GUCs) (§8.2 from the manual)
syn keyword sqlConstant backend gdal_datapath gdal_enabled_drivers enable_outdb_rasters

" Variables
syn match sqlVariable    "\<_[A-Za-z0-9][A-Za-z0-9_]*\>"

" Numbers
syn match sqlNumber      "-\=\<\d*\.\=[0-9_]\>"

" Strings
syn region sqlIdentifier start=+"+  skip=+\\\\\|\\"+  end=+"+
syn region sqlString     start=+'+  skip=+\\\\\|\\'+  end=+'+ contains=@Spell

" Comments
syn region sqlComment    start="/\*" end="\*/" contains=sqlTodo,@Spell
syn match  sqlComment    "#.*$"                contains=sqlTodo,@Spell
syn match  sqlComment    "--.*$"               contains=sqlTodo,@Spell

syn sync ccomment sqlComment

" Options
syn keyword sqlOption    client_min_messages search_path

" Error Codes
syn keyword sqlErrorCode successful_completion warning dynamic_result_sets_returned
syn keyword sqlErrorCode implicit_zero_bit_padding null_value_eliminated_in_set_function
syn keyword sqlErrorCode privilege_not_granted privilege_not_revoked string_data_right_truncation
syn keyword sqlErrorCode deprecated_feature no_data no_additional_dynamic_result_sets_returned
syn keyword sqlErrorCode sql_statement_not_yet_complete connection_exception
syn keyword sqlErrorCode connection_does_not_exist connection_failure
syn keyword sqlErrorCode sqlclient_unable_to_establish_sqlconnection
syn keyword sqlErrorCode sqlserver_rejected_establishment_of_sqlconnection
syn keyword sqlErrorCode transaction_resolution_unknown protocol_violation triggered_action_exception
syn keyword sqlErrorCode feature_not_supported invalid_transaction_initiation locator_exception
syn keyword sqlErrorCode invalid_locator_specification invalid_grantor invalid_grant_operation
syn keyword sqlErrorCode invalid_role_specification diagnostics_exception
syn keyword sqlErrorCode stacked_diagnostics_accessed_without_active_handler
syn keyword sqlErrorCode case_not_found cardinality_violation data_exception array_subscript_error
syn keyword sqlErrorCode character_not_in_repertoire datetime_field_overflow division_by_zero
syn keyword sqlErrorCode error_in_assignment escape_character_conflict indicator_overflow
syn keyword sqlErrorCode interval_field_overflow invalid_argument_for_logarithm
syn keyword sqlErrorCode invalid_argument_for_ntile_function invalid_argument_for_nth_value_function
syn keyword sqlErrorCode invalid_argument_for_power_function invalid_argument_for_width_bucket_function
syn keyword sqlErrorCode invalid_character_value_for_cast invalid_datetime_format
syn keyword sqlErrorCode invalid_escape_character invalid_escape_octet invalid_escape_sequence
syn keyword sqlErrorCode nonstandard_use_of_escape_character invalid_indicator_parameter_value
syn keyword sqlErrorCode invalid_parameter_value invalid_regular_expression
syn keyword sqlErrorCode invalid_row_count_in_limit_clause invalid_row_count_in_result_offset_clause
syn keyword sqlErrorCode invalid_time_zone_displacement_value invalid_use_of_escape_character
syn keyword sqlErrorCode most_specific_type_mismatch null_value_not_allowed
syn keyword sqlErrorCode null_value_no_indicator_parameter numeric_value_out_of_range
syn keyword sqlErrorCode string_data_length_mismatch string_data_right_truncation substring_error
syn keyword sqlErrorCode trim_error unterminated_c_string zero_length_character_string
syn keyword sqlErrorCode floating_point_exception invalid_text_representation
syn keyword sqlErrorCode invalid_binary_representation bad_copy_file_format untranslatable_character
syn keyword sqlErrorCode not_an_xml_document invalid_xml_document invalid_xml_content invalid_xml_comment
syn keyword sqlErrorCode invalid_xml_processing_instruction integrity_constraint_violation
syn keyword sqlErrorCode restrict_violation not_null_violation foreign_key_violation unique_violation
syn keyword sqlErrorCode check_violation exclusion_violation invalid_cursor_state invalid_transaction_state
syn keyword sqlErrorCode active_sql_transaction branch_transaction_already_active
syn keyword sqlErrorCode held_cursor_requires_same_isolation_level
syn keyword sqlErrorCode inappropriate_access_mode_for_branch_transaction
syn keyword sqlErrorCode inappropriate_isolation_level_for_branch_transaction
syn keyword sqlErrorCode no_active_sql_transaction_for_branch_transaction
syn keyword sqlErrorCode read_only_sql_transaction schema_and_data_statement_mixing_not_supported
syn keyword sqlErrorCode no_active_sql_transaction in_failed_sql_transaction invalid_sql_statement_name
syn keyword sqlErrorCode triggered_data_change_violation invalid_authorization_specification
syn keyword sqlErrorCode invalid_password dependent_privilege_descriptors_still_exist
syn keyword sqlErrorCode dependent_objects_still_exist invalid_transaction_termination
syn keyword sqlErrorCode sql_routine_exception function_executed_no_return_statement
syn keyword sqlErrorCode modifying_sql_data_not_permitted prohibited_sql_statement_attempted
syn keyword sqlErrorCode reading_sql_data_not_permitted invalid_cursor_name external_routine_exception
syn keyword sqlErrorCode containing_sql_not_permitted modifying_sql_data_not_permitted
syn keyword sqlErrorCode prohibited_sql_statement_attempted reading_sql_data_not_permitted
syn keyword sqlErrorCode external_routine_invocation_exception invalid_sqlstate_returned
syn keyword sqlErrorCode null_value_not_allowed trigger_protocol_violated srf_protocol_violated
syn keyword sqlErrorCode savepoint_exception invalid_savepoint_specification invalid_catalog_name
syn keyword sqlErrorCode invalid_schema_name transaction_rollback transaction_integrity_constraint_violation
syn keyword sqlErrorCode serialization_failure statement_completion_unknown deadlock_detected
syn keyword sqlErrorCode syntax_error_or_access_rule_violation syntax_error insufficient_privilege
syn keyword sqlErrorCode cannot_coerce grouping_error windowing_error invalid_recursion invalid_foreign_key
syn keyword sqlErrorCode invalid_name name_too_long reserved_name datatype_mismatch indeterminate_datatype
syn keyword sqlErrorCode collation_mismatch indeterminate_collation wrong_object_type undefined_column
syn keyword sqlErrorCode undefined_function undefined_table undefined_parameter undefined_object
syn keyword sqlErrorCode duplicate_column duplicate_cursor duplicate_database duplicate_function
syn keyword sqlErrorCode duplicate_prepared_statement duplicate_schema duplicate_table duplicate_alias
syn keyword sqlErrorCode duplicate_object ambiguous_column ambiguous_function ambiguous_parameter
syn keyword sqlErrorCode ambiguous_alias invalid_column_reference invalid_column_definition
syn keyword sqlErrorCode invalid_cursor_definition invalid_database_definition invalid_function_definition
syn keyword sqlErrorCode invalid_prepared_statement_definition invalid_schema_definition
syn keyword sqlErrorCode invalid_table_definition invalid_object_definition with_check_option_violation
syn keyword sqlErrorCode insufficient_resources disk_full out_of_memory too_many_connections
syn keyword sqlErrorCode configuration_limit_exceeded program_limit_exceeded statement_too_complex
syn keyword sqlErrorCode too_many_columns too_many_arguments object_not_in_prerequisite_state object_in_use
syn keyword sqlErrorCode cant_change_runtime_param lock_not_available operator_intervention query_canceled
syn keyword sqlErrorCode admin_shutdown crash_shutdown cannot_connect_now database_dropped system_error
syn keyword sqlErrorCode io_error undefined_file duplicate_file config_file_error lock_file_exists
syn keyword sqlErrorCode fdw_error fdw_column_name_not_found fdw_dynamic_parameter_value_needed
syn keyword sqlErrorCode fdw_function_sequence_error fdw_inconsistent_descriptor_information
syn keyword sqlErrorCode fdw_invalid_attribute_value fdw_invalid_column_name fdw_invalid_column_number
syn keyword sqlErrorCode fdw_invalid_data_type fdw_invalid_data_type_descriptors
syn keyword sqlErrorCode fdw_invalid_descriptor_field_identifier
syn keyword sqlErrorCode fdw_invalid_handle fdw_invalid_option_index fdw_invalid_option_name
syn keyword sqlErrorCode fdw_invalid_string_length_or_buffer_length fdw_invalid_string_format
syn keyword sqlErrorCode fdw_invalid_use_of_null_pointer fdw_too_many_handles fdw_out_of_memory
syn keyword sqlErrorCode fdw_no_schemas fdw_option_name_not_found fdw_reply_handle fdw_schema_not_found
syn keyword sqlErrorCode fdw_table_not_found fdw_unable_to_create_execution fdw_unable_to_create_reply
syn keyword sqlErrorCode fdw_unable_to_establish_connection plpgsql_error raise_exception no_data_found
syn keyword sqlErrorCode too_many_rows internal_error data_corrupted index_corrupted

" Extensions
syn keyword sqlExtension plpgsql plpythonu plpython plperl plpgsqlu hstore adminpack auth_delay
syn keyword sqlExtension auto_explain btree_gin btree_gist chkpass citext cube dblink dict_int
syn keyword sqlExtension dict_xsyn dummy_seclabel earthdistance file_fdw fuzzystrmatch intagg
syn keyword sqlExtension intarray isn lo ltree pageinspect passwordcheck pg_buffercache pgcrypto
syn keyword sqlExtension pg_freespacemap pg_prewarm pgrowlocks pg_stat_statements pgstattuple
syn keyword sqlExtension pg_trgm postgres_fdw seg sepgsql spi sslinfo tablefunc tcn test_decoding
syn keyword sqlExtension test_parser test_shm_mq tsearch2 unaccent uuid-ossp xml2

" Psql Keywords
syn keyword sqlPsqlKeyword cd conninfo echo qecho prompt pset setenv timing unset

" Todo
syn keyword sqlTodo contained TODO FIXME XXX DEBUG NOTE

" PL/pgSQL
syn region plpgsql start=+\$pgsql\$+ end=+\$pgsql\$+ keepend contains=ALL
syn region plpgsql start=+\$\$+ end=+\$\$+ keepend contains=ALL

" PL/Python
syn include @Python syntax/python.vim
syn region plPython start=+\$python\$+ end=+\$python\$+ keepend contains=@Python

" Syntax Synchronizing
syn sync minlines=10 maxlines=100

" Default highlighting
command -nargs=+ HiLink hi def link <args>

HiLink sqlComment        Comment
HiLink sqlConstant       Constant
HiLink sqlErrorCode      Special
HiLink sqlExtension      Type
HiLink sqlFunction       Function
HiLink sqlIdentifier     Identifier
HiLink sqlKeyword        sqlSpecial
HiLink sqlNumber         Number
HiLink sqlOperator       sqlStatement
HiLink sqlOption         Define
HiLink sqlSpecial        Special
HiLink sqlStatement      Statement
HiLink sqlString         String
HiLink sqlType           Type
HiLink sqlTodo           Todo
HiLink sqlVariable       Identifier
HiLink sqlPsqlKeyword    SpecialKey

delcommand HiLink

let b:current_syntax = "sql"

